version: "3.9"

services:
  app:
    build: .
    ports:
      - "8083:8083"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - PORT=8083
      - LOG_LEVEL=info
      - MINIO_ENDPOINT=producer-minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123456
      - MINIO_USE_SSL=false
      - MINIO_BUCKET=ondc-payloads
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_ON_SEARCH_TOPIC=ondc.on_search.pointer
    depends_on:
      - db
      - producer-minio
      - kafka
    networks:
      - shared-platform-network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - shared-platform-network

  producer-minio:
    image: minio/minio:RELEASE.2024-01-05T22-17-24Z
    command: server /data --console-address ":9001"
    container_name: producer-minio
    networks:
      - shared-platform-network
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123456
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    networks:
      - shared-platform-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - shared-platform-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  minio-data:

networks:
  shared-platform-network:
    external: true
